# numpy: package for multidimensional array

In [25]:
#shift tab to check document

In [4]:
# Numpy: Numerical python

In [1]:
import numpy as np

In [3]:
arr=np.array([2,4,6,8])
arr

array([2, 4, 6, 8])

In [5]:
list = [2,5,9]

In [7]:
arr1= np.array(list)
arr1

array([2, 5, 9])

In [19]:
print(type((2,5,7)))
arr2=np.array((2,5,7))
arr2

<class 'tuple'>


array([2, 5, 7])

In [5]:
ar=np.array({'a':1,'b':2,'c':5,'d':7})
ar

array({'a': 1, 'b': 2, 'c': 5, 'd': 7}, dtype=object)

### np.array takes only one argument

In [12]:
list3 = [[1,2,3],[4,5,6],[7,8,9]]

In [13]:
arr3=np.array(list2)
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [20]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(2,19,3)

array([ 2,  5,  8, 11, 14, 17])

In [20]:
np.arange((2,19,3))

TypeError: arange: scalar arguments expected instead of a tuple.

In [4]:
np.arange(33,dtype='float')

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32.])

In [5]:
np.arange(19,33,dtype='float')

array([19., 20., 21., 22., 23., 24., 25., 26., 27., 28., 29., 30., 31.,
       32.])

In [6]:
np.range(12)

AttributeError: module 'numpy' has no attribute 'range'

In [28]:
np.zeros(13)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
np.zeros(13,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [2]:
import numpy as np

In [11]:
np.zeros((3,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [9]:
np.zeros(3,7,int)

TypeError: Cannot interpret '7' as a data type

In [8]:
np.zeros((3,7),int)


array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [12]:
np.zeros((3,7),bool)

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False]])

In [3]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [4]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
np.ones((2,3),int)

array([[1, 1, 1],
       [1, 1, 1]])

In [14]:
np.ones((2,5,3),int)

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

### linspace creates 5 elements with equal difference in range 0 to 1

In [6]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [2]:
np.linspace(0,4,7)

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        ])

### identity matrixx

In [45]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### transpose of array

In [48]:
b=a.T
b

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
ar=np.array([[1, 4, 8.],
       [1., 2., 0.],
       [0., 3., 4.8]])
ar.T        

array([[1. , 1. , 0. ],
       [4. , 2. , 3. ],
       [8. , 0. , 4.8]])

In [18]:
ar=np.array([[1, 4, 8],
       [1, 2, 0],
       [0, 3, 4]])
ar.T 

array([[1, 1, 0],
       [4, 2, 3],
       [8, 0, 4]])

### creates random multiple dimensional array between range 0 to 1

In [21]:
np.random(7)

TypeError: 'module' object is not callable

In [3]:
np.random()

TypeError: 'module' object is not callable

In [7]:
np.random.randint(7)

0

In [51]:
np.random.randint(7,17)

15

In [29]:
np.random.randint(7,17,3)

array([12, 16,  7])

In [43]:
np.random.randfloat(7)

AttributeError: module 'numpy.random' has no attribute 'randfloat'

In [30]:
np.random.rand()

0.8443980989772946

In [53]:
np.random.rand(4)

array([0.2401639 , 0.69260111, 0.82852286, 0.57058877])

In [18]:
np.random.rand(2,4)

array([[0.06586349, 0.5904037 , 0.5072304 , 0.18581179],
       [0.67492958, 0.51459608, 0.40632418, 0.13163054]])

### creates +ive and -ive random multiple dimensional array between range 0 to 1

In [54]:
np.random.randn(5)

array([ 1.3459981 , -3.29926823, -0.36667053,  0.06307697, -1.37939462])

In [19]:
np.random.randn(2,5)

array([[-0.42188931,  0.85929972, -0.65025117, -1.78303297, -1.96206034],
       [ 0.29590774,  1.29844781,  0.11498361,  0.85296701, -0.8937523 ]])

### gives random integer . 2nd is optional else 2nd arg must be greater than first . 3rd is number of elements 

In [21]:
np.random.randint(87)

86

In [26]:
np.random.randint(9,87)

32

In [30]:
np.random.randint(23,8)

ValueError: low >= high

In [31]:
np.random.randint(14,75,17)

array([15, 29, 24, 66, 22, 67, 66, 55, 20, 31, 17, 34, 72, 65, 36, 19, 38])

In [35]:
arr2= np.random.randint(13,67,25)
arr2

array([29, 25, 36, 23, 49, 40, 31, 48, 63, 64, 43, 55, 46, 19, 44, 59, 39,
       29, 37, 27, 54, 29, 16, 42, 54])

In [57]:
arr3=np.arange(30)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

### 9*7 = 63 which is range of array or total length of array else throws errror

In [58]:
arr4=arr3.reshape(6,5)
arr4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [44]:
arr3.reshape(9,8)

ValueError: cannot reshape array of size 63 into shape (9,8)

In [60]:
arr3.max()

29

### gives index of max element in array

In [62]:
arr3.argmax()

29

In [63]:
arr3.argmin()

0

### transposed the matrixx

In [52]:
arr5=arr4.T
arr5

array([[ 0,  7, 14, 21, 28, 35, 42, 49, 56],
       [ 1,  8, 15, 22, 29, 36, 43, 50, 57],
       [ 2,  9, 16, 23, 30, 37, 44, 51, 58],
       [ 3, 10, 17, 24, 31, 38, 45, 52, 59],
       [ 4, 11, 18, 25, 32, 39, 46, 53, 60],
       [ 5, 12, 19, 26, 33, 40, 47, 54, 61],
       [ 6, 13, 20, 27, 34, 41, 48, 55, 62]])

In [54]:
sample_array=np.arange(3,79)
sample_array

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
       71, 72, 73, 74, 75, 76, 77, 78])

### multiple assignments by 1 element at once 

In [56]:
sample_array[3:17]=100
sample_array

array([  3,   4,   5, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100,  20,  21,  22,  23,  24,  25,  26,  27,  28,
        29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
        42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,
        55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,
        68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78])

In [59]:
sample_array2=sample_array[16:25]
sample_array2

array([100,  20,  21,  22,  23,  24,  25,  26,  27])

In [60]:
sample_array2[:]=220
sample_array2

array([220, 220, 220, 220, 220, 220, 220, 220, 220])

In [2]:
import numpy as np

### always takes elements as a list not as a tuple or anything else can use [ ] or ( )

In [32]:
multiar=np.array(([34,56,78,66],[98,76,65,44],[54,32,11,77],[23,43,57,85]))
multiar

array([[34, 56, 78, 66],
       [98, 76, 65, 44],
       [54, 32, 11, 77],
       [23, 43, 57, 85]])

In [9]:
multiar[2,3]

77

In [71]:
multiar[3]

array([23, 43, 57, 85])

In [73]:
multiar[3:]

array([[23, 43, 57, 85]])

In [72]:
multiar[3,:]

array([23, 43, 57, 85])

In [74]:
multiar[3][:]

array([23, 43, 57, 85])

In [69]:
multiar[[3][:]]

NameError: name 'multiar' is not defined

### 1st to 2nd column , all rows

In [34]:
multiar[:,1:3]

array([[56, 78],
       [76, 65],
       [32, 11],
       [43, 57]])

### brackets are imp, else gives error as total are 3 indexes

In [37]:
multiar[:,2,1]

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

### all rows for columns 3 and 1 (excluding 2). first 3 and then 1. order matters

In [32]:
multiar[:,(3,1)]

array([[66, 56],
       [44, 76],
       [77, 32],
       [85, 43]])

### all rows for columns 1 and 2. first 1 and then 2

In [39]:
multiar[:,(1,2)]

array([[56, 78],
       [76, 65],
       [32, 11],
       [43, 57]])

In [4]:
multiar

array([[34, 56, 78, 66],
       [98, 76, 65, 44],
       [54, 32, 11, 77],
       [23, 43, 57, 85]])

In [5]:
multiar[(1,3)]

44

In [7]:
# element at :
# 2nd(1) row and 2nd(1) column  &  4th(3) row and 3rd(2) column

In [75]:
multiar[(1,3),(1,2)]

array([76, 57])

In [50]:
Arr1=[3,2,45,23,67,53,75,92]
print(Arr1)
Arr2=np.arange(5,13)
print(Arr2)

[3, 2, 45, 23, 67, 53, 75, 92]
[ 5  6  7  8  9 10 11 12]


In [52]:
### adds 1st element of arr1 with 1st element of arr2

In [51]:
Arr1 + Arr2

array([  8,   8,  52,  31,  76,  63,  86, 104])

In [9]:
Ar1=[3,2,45,23,67,53,75,92]
print(Ar1)
Ar2=np.arange(5,12)
print(Ar2)

[3, 2, 45, 23, 67, 53, 75, 92]
[ 5  6  7  8  9 10 11]


In [10]:
Ar1 + Ar2

ValueError: operands could not be broadcast together with shapes (8,) (7,) 

In [53]:
np.exp(Arr1)

array([2.00855369e+01, 7.38905610e+00, 3.49342711e+19, 9.74480345e+09,
       1.25236317e+29, 1.04137594e+23, 3.73324200e+32, 9.01762841e+39])

In [54]:
np.sqrt(Arr1)

array([1.73205081, 1.41421356, 6.70820393, 4.79583152, 8.18535277,
       7.28010989, 8.66025404, 9.59166305])

In [55]:
np.log(Arr1)

array([1.09861229, 0.69314718, 3.80666249, 3.13549422, 4.20469262,
       3.97029191, 4.31748811, 4.52178858])

In [56]:
np.max(Arr1)

92

In [59]:
np.argmax(Arr1)

7

In [57]:
np.min(Arr1)

2

In [60]:
np.argmin(Arr1)

1

In [61]:
np.square(Arr1)

array([   9,    4, 2025,  529, 4489, 2809, 5625, 8464])

### standard deviation

In [62]:
np.std(Arr1)

31.132780152116194

### variance

In [63]:
np.var(Arr1)

969.25

In [67]:
np.mean(Arr1)

45.0

In [68]:
np.sort(Arr1)

array([ 2,  3, 23, 45, 53, 67, 75, 92])

In [65]:
np.median(Arr1)

49.0

In [66]:
np.mode(Arr1)

AttributeError: module 'numpy' has no attribute 'mode'

In [86]:
np.random.randn(5,7)


array([[ 1.17889525, -0.24175871,  1.17534069,  0.57921285,  1.2977842 ,
         0.30359675,  0.12018671],
       [ 1.1245672 ,  1.3225105 , -0.30305408, -0.33742329,  0.79964701,
        -0.89003749,  1.30952703],
       [ 0.85402675,  1.08438612,  2.50995082, -1.69675992,  0.73939341,
        -0.71943503,  0.48387704],
       [ 0.36554773, -0.87076573, -2.5411204 , -0.01200144,  0.73432542,
         1.12457949, -0.77280926],
       [ 0.04766683,  0.40690271,  0.92497585,  0.79834685, -1.57971692,
         0.45736912,  1.17327087]])

In [79]:
Arr3=[45.12345,32.3425,65.3,47.78,32,62.986,87.000,32.3425]

In [80]:
np.round(Arr3)

array([45., 32., 65., 48., 32., 63., 87., 32.])

In [81]:
np.round(Arr3,decimals=2)

array([45.12, 32.34, 65.3 , 47.78, 32.  , 62.99, 87.  , 32.34])

In [82]:
np.unique(Arr3)

array([32.     , 32.3425 , 45.12345, 47.78   , 62.986  , 65.3    ,
       87.     ])

In [11]:
sports=["cricket",'football',"basketball",'crick','basketball']

### gives unqiue and arranges them alphabetically

In [84]:
np.unique(sports)

array(['basketball', 'crick', 'cricket', 'football'], dtype='<U10')

In [12]:
np.nunique(sports)

AttributeError: module 'numpy' has no attribute 'nunique'