In [1]:
## numpy session 2

In [1]:
import numpy as np

## creating #vector or 1d array

In [5]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [7]:
ar1=np.array([1,2,3,4,5])
ar1

array([1, 2, 3, 4, 5])

## 2d array or #matrix

In [10]:
ar2= np.array([1,2,3],[4,5,6])

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [12]:
ar2= np.array([[1,2,3],[4,5,6]])
ar2

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [17]:
a3=np.arange(27).reshape(3,3)
a3

ValueError: cannot reshape array of size 27 into shape (3,3)

In [2]:
a3=np.arange(27).reshape(9,3)
a3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [19]:
ar1.shape

(5,)

In [20]:
ar2.shape

(2, 3)

# Assignment 

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
df1=pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user")
df1

user_id|age|gender|occupation|zip_code
0                  1|24|M|technician|85711
1                       2|53|F|other|94043
2                      3|23|M|writer|32067
3                  4|24|M|technician|43537
4                       5|33|F|other|15213
..                                     ...
938                 939|26|F|student|33319
939           940|32|M|administrator|02215
940                 941|20|M|student|97229
941               942|48|F|librarian|78209
942                 943|22|M|student|77841

[943 rows x 1 columns]

In [ ]:
## 

In [51]:
users=pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user",sep='|')
users

user_id  age gender     occupation zip_code
0          1   24      M     technician    85711
1          2   53      F          other    94043
2          3   23      M         writer    32067
3          4   24      M     technician    43537
4          5   33      F          other    15213
..       ...  ...    ...            ...      ...
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

[943 rows x 5 columns]

## Assign it to a variable called users and use the 'user_id' as index

In [53]:
### set_index of users to users['user_id']

In [52]:
users=users.set_index('user_id')
users

age gender     occupation zip_code
user_id                                    
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
...      ...    ...            ...      ...
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

[943 rows x 4 columns]

In [54]:
df1.head(25)

user_id|age|gender|occupation|zip_code
0                 1|24|M|technician|85711
1                      2|53|F|other|94043
2                     3|23|M|writer|32067
3                 4|24|M|technician|43537
4                      5|33|F|other|15213
5                  6|42|M|executive|98101
6              7|57|M|administrator|91344
7              8|36|M|administrator|05201
8                    9|29|M|student|01002
9                    10|53|M|lawyer|90703
10                    11|39|F|other|30329
11                    12|28|F|other|06405
12                 13|47|M|educator|29206
13                14|45|M|scientist|55106
14                 15|49|F|educator|97301
15            16|21|M|entertainment|10309
16               17|30|M|programmer|06355
17                    18|35|F|other|37212
18                19|40|M|librarian|02138
19                20|42|F|homemaker|95660
20                   21|26|M|writer|30068
21                   22|25|M|writer|40206
22                   23|30|F|artist|48197
23                   24|21|F|artist|94533
24                 25|39|M|engineer|55107

In [55]:
df1.tail(10)

user_id|age|gender|occupation|zip_code
933                934|61|M|engineer|22902
934                  935|42|M|doctor|66221
935                   936|24|M|other|32789
936                937|48|M|educator|98072
937              938|38|F|technician|55038
938                 939|26|F|student|33319
939           940|32|M|administrator|02215
940                 941|20|M|student|97229
941               942|48|F|librarian|78209
942                 943|22|M|student|77841

## number of observations or rows in the dataset?

In [58]:
users.shape[0]

943

### number of columns in the dataset?

In [59]:
users.shape[1]

4

## Print the name of all the columns.

In [ ]:
users[]

In [39]:
users['occupation']

0         technician
1              other
2             writer
3         technician
4              other
           ...      
938          student
939    administrator
940          student
941        librarian
942          student
Name: occupation, Length: 943, dtype: object

## How is the dataset indexed?

## What is the data type of each column?

In [62]:
users.dtype

NameError: name 'dtype' is not defined

## Print only the occupation column

In [63]:
users['occupation']

user_id
1         technician
2              other
3             writer
4         technician
5              other
           ...      
939          student
940    administrator
941          student
942        librarian
943          student
Name: occupation, Length: 943, dtype: object

## How many different occupations are in this dataset?

## most frequent occupation?

In [64]:
max(users['occupation'])

'writer'

##  Summarize the DataFrame.

In [ ]:
##Summarize all the columns

In [ ]:
## Summarize only the occupation column

In [ ]:
## What is the mean age of users?

In [71]:
np.mean(users['age'])

34.05196182396607

In [ ]:
## What is the age with least occurrence?

NameError: name 'count' is not defined

In [41]:
users.describe

<bound method NDFrame.describe of      user_id  age gender     occupation zip_code
0          1   24      M     technician    85711
1          2   53      F          other    94043
2          3   23      M         writer    32067
3          4   24      M     technician    43537
4          5   33      F          other    15213
..       ...  ...    ...            ...      ...
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

[943 rows x 5 columns]>

In [47]:
users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 943 entries, 0 to 942
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   user_id     943 non-null    int64 
 1   age         943 non-null    int64 
 2   gender      943 non-null    object
 3   occupation  943 non-null    object
 4   zip_code    943 non-null    object
dtypes: int64(2), object(3)
memory usage: 37.0+ KB
